spring.application.name=cucucook

#spring.datasource.url=jdbc:postgresql://cucucook-database.cr2woqy68hvq.ap-northeast-2.rds.amazonaws.com:5432/postgres
#spring.datasource.username=cucucook
#spring.datasource.password=wldmspfla
#spring.datasource.driver-class-name=org.postgresql.Driver

spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=cucucook
spring.datasource.password=wldmspfla
spring.datasource.driver-class-name=org.postgresql.Driver


# JPA 설정 (옵션)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#콘솔 디버그모드로 보고싶을때 주석해제
#logging.level.org.springframework=DEBUG
#logging.level.org.hibernate=DEBUG
#logging.level.org.springframework.jdbc=DEBUG