spring.profiles.active=local
spring.profiles.group.local=local, common, secret
spring.profiles.group.real_server=real_server, common, secret
server.env:local
#---
spring.config.activate.on-profile:local
server.port=8080
server.serverAddress:http://" + localhost + ":3000
serverName= local_server
spring.datasource.url=jdbc:log4jdbc:postgresql://localhost:5432/postgres
file.dir=D:/cucucook/project/cucucook_files/
file.web.dir=/cucucookFiles/

#---
spring.config.activate.on-profile:real_server
server.port=8080
server.serverAddress=https://cucucook.site
serverName= real_server
spring.datasource.url=jdbc:log4jdbc:postgresql://cucucook-database.cr2woqy68hvq.ap-northeast-2.rds.amazonaws.com:5432/postgres
file.dir=/home/ubuntu/project/cucucook_files/
file.web.dir=/cucucookFiles/

#---
spring.config.activate.on-profile=common
spring.application.name=cucucook

# DB 로그 확인을 위해 아래와 같이 설정 변경
spring.datasource.driver-class-name=net.sf.log4jdbc.sql.jdbcapi.DriverSpy

# HikariCP 설정
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.pool-name=HikariCP
spring.datasource.hikari.auto-commit=false

# MyBatis 설정
# MyBatis mapper 위치
mybatis.mapper-locations=classpath:mapper/*.xml
mybatis.type-aliases-package=com.example.cucucook.domain
# 자동매핑설정
mybatis.configuration.auto-mapping-behavior=partial
# db컬럼이름 > Java객체 필드 매핑시 member_id > memberId로 변환할 수 있도록
mybatis.configuration.map-underscore-to-camel-case=true
mybatis.configuration.log-impl=org.apache.ibatis.logging.slf4j.Slf4jImpl

# HTML, CSS 등의 정적 리소스 파일이 변경되면 브라우저가 자동으로 리로드
spring.devtools.livereload.enabled=true
# 자동재시작
spring.devtools.restart.enabled=true

# 폼데이터 처리
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# 로그 설정
#logging.file.name=log/app.log
logging.config=classpath:log4j2.xml
spring.main.banner-mode=off