spring.application.name=cucucook

#spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=cucucook
spring.datasource.password=wldmspfla
#spring.datasource.driver-class-name=org.postgresql.Driver

#TO-BE
spring.datasource.url=jdbc:log4jdbc:postgresql://localhost:5432/postgres
spring.datasource.driver-class-name=net.sf.log4jdbc.sql.jdbcapi.DriverSpy


# MyBatis 설정
# MyBatis mapper 위치
mybatis.mapper-locations=classpath:mapper/*.xml
mybatis.type-aliases-package=com.example.cucucook.domain
#자동매핑설정
mybatis.configuration.auto-mapping-behavior=partial
mybatis.configuration.map-underscore-to-camel-case=true


spring.devtools.livereload.enabled=true
spring.devtools.restart.enabled=true



#콘솔 디버그모드로 보고싶을때 주석해제
#logging.level.org.springframework=DEBUG
#logging.level.org.hibernate=DEBUG
#logging.level.org.springframework.jdbc=DEBUG

#jwt토큰키
jwt.secret=YLbBRjJCuem8eQ3DPySNrGn0QpsFn8wETMnoiggkWuI=
jwt.token-validity-in-seconds=3600

#이메일 설정
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=dev.jieun.lee@gmail.com
spring.mail.password=cmbg wtdu axhb fhlt
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

#twilio sms 설정
twilio.account.sid=AC2f3c10ff6bd85623824bf921182f08d9
twilio.auth.token=f1aea315e1d7202c77817faac52e9396
twilio.phone.number=USff9ba68e4695c747e2febf6581b1f1ca




